name: fit-netology-leads



jobs:
  env:
    __IMAGE__: "registry.junglejobs.ru/sever/models"
    __JOB__: fit_netology_leads
  execute_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo xxx
